# Generated by Django 3.2.22 on 2023-11-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minues',
            new_name='time_minutes',
        ),
    ]
